import type { QuestionDef } from './schema';
import type { Answers, IncomeType, LoanPurpose } from '../rules/types';

const PURPOSE_OPTIONS = [
  { value: 'wedding', label: 'Wedding' },
  { value: 'medical', label: 'Medical expense' },
  { value: 'education', label: 'Education' },
  { value: 'home_improvement', label: 'Home improvement' },
  { value: 'debt_consolidation', label: 'Paying off other debt' },
  { value: 'vehicle', label: 'Buying a vehicle' },
  { value: 'business_stock_or_equipment', label: 'Business — stock/equipment' },
  { value: 'business_expansion', label: 'Business — expansion' },
  { value: 'other_consumption', label: 'Other personal expense' },
];

export const CORE_QUESTIONS: QuestionDef[] = [
  {
    id: 'purpose',
    tier: 'core',
    section: 'Loan basics',
    prompt: 'What are you borrowing for?',
    reason: 'Purpose determines which product we route you toward and which questions are relevant next.',
    affects: ['O1', 'O2', 'ROUTE-01', 'ROUTE-03'],
    controlType: 'single_select',
    options: PURPOSE_OPTIONS,
    appliesWhen: () => true,
    allowUnknown: false,
    applyAnswer: (draft, raw) => ({ ...draft, purpose: raw as LoanPurpose }),
  },
  {
    id: 'amountWanted',
    tier: 'core',
    section: 'Loan basics',
    prompt: 'How much do you want to borrow?',
    helpText: 'Enter an amount in rupees.',
    reason: 'This is the amount we compare against your safe and lender-likely limits.',
    affects: ['O1', 'O2', 'O4'],
    controlType: 'currency_number',
    appliesWhen: () => true,
    allowUnknown: false,
    applyAnswer: (draft, raw) => ({ ...draft, amountWanted: Number(raw) || 0 }),
  },
  {
    id: 'productHint',
    tier: 'core',
    section: 'Loan basics',
    prompt: 'Do you already have a specific loan/product in mind?',
    helpText: "Pick 'Not sure' if you just want us to figure out what fits.",
    reason: 'If you already know the product, we use it directly instead of guessing from purpose alone.',
    affects: ['ROUTE-01'],
    controlType: 'single_select',
    options: [
      { value: 'unspecified', label: 'Not sure — figure it out for me' },
      { value: 'personal_loan', label: 'Personal loan' },
      { value: 'loan_against_property', label: 'Loan against property' },
      { value: 'business_loan_secured', label: 'Business loan (secured)' },
      { value: 'gold_loan', label: 'Gold loan' },
      { value: 'two_wheeler_loan', label: 'Two-wheeler loan' },
      { value: 'home_loan', label: 'Home loan' },
    ],
    appliesWhen: () => true,
    allowUnknown: true,
    applyAnswer: (draft, raw) => ({
      ...draft,
      productHint: raw === 'unspecified' ? 'unknown' : (raw as Answers['productHint']),
    }),
  },
  {
    id: 'incomeType',
    tier: 'core',
    section: 'Income',
    prompt: 'How would you describe your income?',
    reason: 'This determines how we calculate a reliable income figure and which follow-up questions apply.',
    affects: ['INC-01', 'INC-02', 'INC-03'],
    controlType: 'single_select',
    options: [
      { value: 'salaried', label: 'Salaried — regular monthly pay' },
      { value: 'self_employed', label: 'Self-employed / business owner' },
      { value: 'informal', label: 'Informal / gig / daily-wage income' },
    ],
    appliesWhen: () => true,
    allowUnknown: false,
    applyAnswer: (draft, raw) => ({ ...draft, incomeType: raw as IncomeType }),
  },
  {
    id: 'netMonthlyIncomeSalaried',
    tier: 'core',
    section: 'Income',
    prompt: 'What is your net (take-home) monthly income?',
    reason: 'Your reliable income is the base of every affordability calculation.',
    affects: ['INC-01', 'AFF-01', 'AFF-02', 'O1', 'O2', 'O4'],
    controlType: 'currency_number',
    appliesWhen: (d) => d.incomeType === 'salaried',
    allowUnknown: false,
    applyAnswer: (draft, raw) => ({
      ...draft,
      netMonthlyIncomeSalaried: raw === '' || raw === 'unknown' ? 'unknown' : Number(raw),
    }),
  },
  {
    id: 'monthlyIncomeRange',
    tier: 'core',
    section: 'Income',
    prompt: 'What does your monthly income typically range between?',
    helpText: "It's fine if this varies a lot month to month — give your usual low and high.",
    reason: 'For variable income, we use the low end to plan safely rather than an average.',
    affects: ['INC-01', 'INC-02', 'AFF-01', 'AFF-02', 'O1', 'O2', 'O4'],
    controlType: 'currency_range',
    appliesWhen: (d) => d.incomeType === 'self_employed' || d.incomeType === 'informal',
    allowUnknown: false,
    applyAnswer: (draft, raw) => {
      const { low, high } = raw as { low: number; high: number };
      return { ...draft, monthlyIncomeRangeLow: low, monthlyIncomeRangeHigh: high };
    },
  },
  {
    id: 'existingMonthlyEMI',
    tier: 'core',
    section: 'Existing debt',
    prompt: 'What do you currently pay each month across all existing loans/EMIs?',
    helpText: 'Include everything — car, personal, app loans, credit card minimums you always pay.',
    reason: 'Existing EMI reduces how much new EMI you can safely take on.',
    affects: ['AFF-01', 'AFF-03', 'AFF-04', 'O1', 'O2', 'O4'],
    controlType: 'currency_number',
    appliesWhen: () => true,
    allowUnknown: true,
    applyAnswer: (draft, raw) => ({ ...draft, existingMonthlyEMI: raw === 'unknown' ? 'unknown' : Number(raw) || 0 }),
  },
  {
    id: 'householdMonthlyExpenses',
    tier: 'core',
    section: 'Household',
    prompt: 'What are your monthly household/living expenses, not counting loan EMIs?',
    helpText: 'Rent, groceries, school fees, utilities — your regular cost of living.',
    reason:
      'This sets a floor for what must be left over after any new EMI — it can be the real limit even when income looks sufficient on paper.',
    affects: ['AFF-02', 'AFF-03', 'AFF-05', 'O1', 'O2', 'O4'],
    controlType: 'currency_number',
    appliesWhen: () => true,
    allowUnknown: true,
    applyAnswer: (draft, raw) => ({
      ...draft,
      householdMonthlyExpenses: raw === 'unknown' ? 'unknown' : Number(raw) || 0,
    }),
  },
  {
    id: 'ageYears',
    tier: 'core',
    section: 'Profile',
    prompt: 'What is your age?',
    reason: 'Age caps the maximum tenure we can responsibly recommend.',
    affects: ['TEN-02', 'TEN-03', 'O4'],
    controlType: 'number',
    appliesWhen: () => true,
    allowUnknown: false,
    applyAnswer: (draft, raw) => ({ ...draft, ageYears: Number(raw) || 0 }),
  },
  {
    id: 'creditScore',
    tier: 'core',
    section: 'Credit',
    prompt: 'What is your credit score?',
    helpText: "Pick 'No credit history' if you've never had a formal loan or card, or 'I don't know' if you simply haven't checked.",
    reason: 'Score is a primary anchor for your fair rate band. An unknown score widens the band — it is never treated as a bad score.',
    affects: ['RATE-01', 'RATE-03', 'O3'],
    controlType: 'credit_score_or_unknown',
    appliesWhen: () => true,
    allowUnknown: true,
    applyAnswer: (draft, raw) => {
      if (raw === 'no_score') return { ...draft, creditScore: 'no_score' };
      if (raw === 'unknown') return { ...draft, creditScore: 'unknown' };
      return { ...draft, creditScore: Number(raw) || 'unknown' };
    },
  },
  {
    id: 'recentBounce',
    tier: 'core',
    section: 'Credit',
    prompt: 'Have you missed or bounced an EMI/loan payment in the last 12 months?',
    reason: 'A recent missed payment is one of the strongest signals of real repayment stress.',
    affects: ['VER-01', 'VER-02', 'RATE-02', 'O1', 'O3'],
    controlType: 'yes_no_unknown',
    appliesWhen: () => true,
    allowUnknown: true,
    applyAnswer: (draft, raw) => ({
      ...draft,
      recentBounce: raw === 'unknown' ? 'unknown' : raw === true || raw === 'yes',
    }),
  },
];
